## Conversor de mascaras utilizando pycococreatortools.py

In [1]:
import sys
import os
sys.path.append('./pycococreator-0.2.0/pycococreatortools')
from pycococreatortools import *
from PIL import Image
import numpy as np
from numpy import asarray

In [2]:
# load the image
#image = Image.open('./IMG/Castings/C0001/masks/C0001_0001_0.png')
image = Image.open('./IMG/Welding/J0001/masks/J0001_0000_0.png')
# convert image to numpy array
data = asarray(image.convert("L"))
print(type(data))
# summarize shape
print(data.shape)

# create Pillow image
image2 = Image.fromarray(data)
print(type(image2))

# summarize image details
print(image2.mode)
print(image2.size)

<class 'numpy.ndarray'>
(570, 736)
<class 'PIL.Image.Image'>
L
(736, 570)


In [3]:
print(data) # MATRIZ DE 0 marcada el area en 1's

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [4]:
poligonos = binary_mask_to_polygon(data)

In [5]:
print(poligonos)

[[128.0, 0.75, 127.25, 0.0, 128.0, 0, 128.75, 0.0, 128.0, 0.75], [133.0, 2.875, 132.0, 2.9705882352941178, 131.02941176470588, 2.0, 132.0, 1.0294117647058822, 132.16666666666666, 1.0, 132.05555555555554, 0.0, 133.0, 0, 133.94444444444446, 0.0, 133.83333333333334, 1.0, 133.875, 2.0, 133.0, 2.875], [138.0, 1.75, 137.0, 1.9166666666666665, 136.0, 1.9166666666666665, 135.0, 1.9705882352941178, 134.02941176470588, 1.0, 134.25, 0.0, 135.0, 0, 135.75, 0.0, 136.0, 0.08333333333333326, 136.5, 0.0, 137.0, 0, 137.5, 0.0, 138.0, 0.25, 138.75, 1.0, 138.0, 1.75], [139.0, 0.5, 138.5, 0.0, 139.0, 0, 139.5, 0.0, 139.0, 0.5], [141.0, 1.75, 140.25, 1.0, 140.03571428571428, 0.0, 141.0, 0, 141.96428571428572, 0.0, 141.75, 1.0, 141.0, 1.75], [143.0, 1.8333333333333335, 142.16666666666666, 1.0, 142.08333333333334, 0.0, 143.0, 0, 143.91666666666666, 0.0, 143.83333333333334, 1.0, 143.0, 1.8333333333333335], [130.0, 3.916666666666667, 129.0, 3.954545454545455, 128.04545454545453, 3.0, 128.07142857142858, 2.0, 1

In [6]:
rle = binary_mask_to_rle(data)

In [7]:
print(rle)

{'counts': [72960, 1, 3, 1, 1, 4, 1, 1, 1, 1, 1, 3, 1, 1, 1, 2, 1, 547, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 550, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 550, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 551, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 547, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 549, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 1, 546, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 548, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 3, 1, 2, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 515, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 3, 1, 2, 3, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 517, 1, 3, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 514, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1,

In [8]:
## ANOTACION 0 de la imagen 0
annotation_id = 1
image_id = 0
tolerance = 2
binary_mask = data
is_crowd = False
category_info = {
        "id": 0,
        "is_crowd": False
    }
if category_info["is_crowd"]:
    print(True)
else:
    print(False)

False


In [9]:
create_annotation_info(annotation_id, image_id, category_info, binary_mask, 
                           image_size=None, tolerance=0, bounding_box=None)

{'id': 1,
 'image_id': 0,
 'category_id': 0,
 'iscrowd': 0,
 'area': 278433,
 'bbox': [128.0, 0.0, 545.0, 570.0],
 'segmentation': [[128.0,
   0.75,
   127.25,
   0.0,
   128.0,
   0,
   128.75,
   0.0,
   128.0,
   0.75],
  [133.0,
   2.875,
   132.0,
   2.9705882352941178,
   131.02941176470588,
   2.0,
   132.0,
   1.0294117647058822,
   132.16666666666666,
   1.0,
   132.05555555555554,
   0.0,
   133.0,
   0,
   133.94444444444446,
   0.0,
   133.83333333333334,
   1.0,
   133.875,
   2.0,
   133.0,
   2.875],
  [138.0,
   1.75,
   137.0,
   1.9166666666666665,
   136.0,
   1.9166666666666665,
   135.0,
   1.9705882352941178,
   134.02941176470588,
   1.0,
   134.25,
   0.0,
   135.0,
   0,
   135.75,
   0.0,
   136.0,
   0.08333333333333326,
   136.5,
   0.0,
   137.0,
   0,
   137.5,
   0.0,
   138.0,
   0.25,
   138.75,
   1.0,
   138.0,
   1.75],
  [139.0, 0.5, 138.5, 0.0, 139.0, 0, 139.5, 0.0, 139.0, 0.5],
  [141.0,
   1.75,
   140.25,
   1.0,
   140.03571428571428,
   0.0,
 

## Creando JSON

# 1. Crear JSON y Array images

In [10]:
"""
 En el directorio "Con Mascara" y en particular "Castings" se recorrera cada carpeta y los ficheros .png
 seran añadidos al array de Imágenes, finalmente escrito en el fichero.
 Formato:
     height
     width
     id
     file_name 
"""
import json

# Pequeña funcion que guarda formateado al fichero el diccionario actual
def guardaJson(dic, fichero):
    with open(fichero, 'w') as fichero:
        json.dump(dic, fichero, indent = 4)
    fichero.close()

''' 
# PRUEBAS

fichero= '.'+os.sep+'IMG'+os.sep+'info.json'

datos = {}

datos['images'] = []
datos['images'].append({
    'height':5,
    'width': 1,
    'id': 'Dale canffdela'
})

datos['images'].append({
    'height':5,
    'width': 21,
    'id': 'Dafasfa'
})

guardaJson(datos,fichero)

''' 

" \n# PRUEBAS\n\nfichero= '.'+os.sep+'IMG'+os.sep+'info.json'\n\ndatos = {}\n\ndatos['images'] = []\ndatos['images'].append({\n    'height':5,\n    'width': 1,\n    'id': 'Dale canffdela'\n})\n\ndatos['images'].append({\n    'height':5,\n    'width': 21,\n    'id': 'Dafasfa'\n})\n\nguardaJson(datos,fichero)\n\n"

In [11]:
''' 
Funcion que recibe un directorio y un nombre para el fichero, escanea solo imagenes y no mascaras y
las registra en la primera seccion del JSON
'''

def registraImages(directorio, nombreJson):
    fichero = '.' + os.sep +'IMG'+ os.sep + nombreJson +'.json'
    datosJson = {}
    extensiones = [".png",".jpg"]
    datosJson['images'] = []
    ID = 0
    for root, dirs, files in os.walk(directorio_imagenes):
        path = root.split(os.sep)
        if (os.path.basename(root) != 'masks'):
            for file in files:
                extension = os.path.splitext(file)[1]
                if extension in extensiones:
                    im = Image.open(root+os.sep+file)
                    height, width = im.size
                    datosJson['images'].append({
                        'height': height,
                        'width': width,
                        'id': ID,
                        'file_name': file
                    })
                    ID+=1
    return datosJson['images']

In [13]:
directorio_imagenes = '.'+os.sep+'IMG'
fichero = 'info'
registraImages(directorio_imagenes, fichero)

[{'height': 736, 'width': 570, 'id': 0, 'file_name': 'J0001_0000.png'},
 {'height': 736, 'width': 570, 'id': 1, 'file_name': 'J0001_0001.png'},
 {'height': 736, 'width': 570, 'id': 2, 'file_name': 'J0001_0002.png'},
 {'height': 736, 'width': 570, 'id': 3, 'file_name': 'J0001_0003.png'},
 {'height': 736, 'width': 570, 'id': 4, 'file_name': 'J0001_0004.png'},
 {'height': 736, 'width': 570, 'id': 5, 'file_name': 'J0001_0005.png'},
 {'height': 736, 'width': 570, 'id': 6, 'file_name': 'J0001_0006.png'},
 {'height': 736, 'width': 570, 'id': 7, 'file_name': 'J0001_0007.png'},
 {'height': 736, 'width': 570, 'id': 8, 'file_name': 'J0001_0008.png'},
 {'height': 736, 'width': 570, 'id': 9, 'file_name': 'J0001_0009.png'},
 {'height': 768, 'width': 366, 'id': 10, 'file_name': 'W0001_0000.png'},
 {'height': 768, 'width': 366, 'id': 11, 'file_name': 'W0001_0001.png'},
 {'height': 768, 'width': 366, 'id': 12, 'file_name': 'W0001_0002.png'},
 {'height': 768, 'width': 366, 'id': 13, 'file_name': 'W0001_

In [14]:
''' 
Funcion que recibe un directorio y un nombre para el fichero, segun las carpetas en IMG, 
genera una nueva categoria

'''

def registraCategories(directorio, nombreJson):
    fichero = '.' + os.sep +'IMG'+ os.sep + nombreJson +'.json'
    
    dir_list = next(os.walk('.' + os.sep +'IMG'))[1]
    
    datosJson = {}
    datosJson['categories'] = []
    ID = 0
    
    for d in dir_list:
        datosJson['categories'].append({
                            'supercategory': 'Defect',
                            'id': ID,
                            'name': d
                        })
        ID+=1
    return datosJson['categories']  
    

In [15]:
fichero = 'info'
registraCategories(directorio_imagenes, fichero)

[{'supercategory': 'Defect', 'id': 0, 'name': 'Welding'}]

In [18]:
''' 
Funcion que recibe un directorio y un nombre para el fichero, recorre imagenes y busca sus mascaras
genera la segmentacion y anotaciones y escribe en el JSON
'''

def registraAnnotations(directorio, nombreJson):
    datosJson = {}    
    fichero = '.' + os.sep +'IMG'+ os.sep + nombreJson +'.json'
    datosJson['images'] = registraImages(directorio_imagenes, fichero)
    datosJson['categories'] = registraCategories(directorio_imagenes, fichero)
    extensiones = [".png",".jpg"]
    datosJson['annotations'] = []
    ID = 0
    IDImagen = 0
    for root, dirs, files in os.walk(directorio_imagenes):
        path = root.split(os.sep)
        if (os.path.basename(root) != 'masks'):
            for file in files:                
                extension = os.path.splitext(file)[1]
                if extension in extensiones:
                    directorio_mascaras = root + os.sep + 'masks'
                    for rootm, dirm, mascaras in os.walk(directorio_mascaras):
                        fileN = file.replace(extension,'')
                        for mascara in mascaras:                      
                            if fileN in mascara:
                                image = Image.open(directorio_mascaras+ os.sep+mascara)
                                #data = asarray(image)
                                data = asarray(image.convert("L"))
                                
                                annotation_id = ID
                                image_id = IDImagen
                                tolerance = 2
                                binary_mask = data
                                is_crowd = False
                                
                                if 'Castings' in path:
                                      category_info = {
                                            "id": 0,
                                            "is_crowd": False
                                        }
                                elif 'Welding' in path:
                                        category_info = {
                                            "id": 1,
                                            "is_crowd": False
                                        }
                                elif 'Welds' in path:
                                        category_info = {
                                            "id": 2,
                                            "is_crowd": False
                                        }
                                    
                                annotation = create_annotation_info(annotation_id, image_id, category_info, binary_mask, 
                           image_size=None, tolerance=2, bounding_box=None)
                                datosJson['annotations'].append(annotation)
                                ID+=1
                    IDImagen+=1
                
    guardaJson(datosJson,fichero)
                                


In [20]:
directorio_imagenes = '.'+os.sep+'IMG'
fichero = 'info'
registraAnnotations(directorio_imagenes, fichero)