## Conversor de mascaras utilizando pycococreatortools.py

In [91]:
import sys
import os
sys.path.append('./pycococreator-0.2.0/pycococreatortools')
from pycococreatortools import *
from PIL import Image
import numpy as np
from numpy import asarray

In [92]:
# load the image
image = Image.open('./IMG/Castings/C0001/masks/C0001_0001_0.png')
# convert image to numpy array
data = asarray(image)
print(type(data))
# summarize shape
print(data.shape)

# create Pillow image
image2 = Image.fromarray(data)
print(type(image2))

# summarize image details
print(image2.mode)
print(image2.size)

<class 'numpy.ndarray'>
(572, 768)
<class 'PIL.Image.Image'>
L
(768, 572)


In [93]:
print(data) # MATRIZ DE 0 marcada el area en 1's

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [94]:
poligonos = binary_mask_to_polygon(data)

In [95]:
print(poligonos)

[[190.0, 492.5, 189.0, 492.5, 188.0, 492.5, 187.0, 492.5, 186.0, 492.5, 185.0, 492.5, 184.0, 492.5, 183.0, 492.5, 182.0, 492.5, 181.0, 492.5, 180.0, 492.5, 179.0, 492.5, 178.5, 492.0, 178.0, 491.5, 177.0, 491.5, 176.5, 491.0, 176.0, 490.5, 175.0, 490.5, 174.5, 490.0, 174.0, 489.5, 173.5, 489.0, 173.0, 488.5, 172.5, 488.0, 172.5, 487.0, 172.0, 486.5, 171.5, 486.0, 171.5, 485.0, 171.0, 484.5, 170.5, 484.0, 170.5, 483.0, 170.5, 482.0, 170.5, 481.0, 170.5, 480.0, 171.0, 479.5, 171.5, 479.0, 171.5, 478.0, 172.0, 477.5, 172.5, 477.0, 172.5, 476.0, 173.0, 475.5, 173.5, 475.0, 174.0, 474.5, 174.5, 474.0, 175.0, 473.5, 176.0, 473.5, 176.5, 473.0, 177.0, 472.5, 178.0, 472.5, 178.5, 472.0, 179.0, 471.5, 180.0, 471.5, 181.0, 471.5, 182.0, 471.5, 183.0, 471.5, 184.0, 471.5, 185.0, 471.5, 186.0, 471.5, 187.0, 471.5, 188.0, 471.5, 189.0, 471.5, 190.0, 471.5, 190.5, 472.0, 191.0, 472.5, 192.0, 472.5, 192.5, 473.0, 193.0, 473.5, 194.0, 473.5, 194.5, 474.0, 195.0, 474.5, 195.5, 475.0, 196.0, 475.5, 196.

In [96]:
rle = binary_mask_to_rle(data)

In [97]:
print(rle)

{'counts': [98292, 5, 565, 9, 561, 13, 558, 15, 556, 17, 555, 17, 554, 19, 553, 19, 552, 21, 551, 21, 551, 21, 551, 21, 551, 21, 551, 21, 551, 21, 551, 21, 551, 21, 551, 21, 551, 21, 551, 21, 552, 19, 553, 19, 554, 17, 555, 17, 556, 15, 558, 13, 561, 9, 565, 5, 325555], 'size': [572, 768]}


In [99]:
## ANOTACION 0 de la imagen 0
annotation_id = 1
image_id = 0
tolerance = 2
binary_mask = data
is_crowd = False
category_info = {
        "id": 0,
        "is_crowd": False
    }
if category_info["is_crowd"]:
    print(True)
else:
    print(False)

False


In [100]:
create_annotation_info(annotation_id, image_id, category_info, binary_mask, 
                           image_size=None, tolerance=2, bounding_box=None)

{'id': 1,
 'image_id': 0,
 'category_id': 0,
 'iscrowd': 0,
 'area': 480,
 'bbox': [171.0, 472.0, 28.0, 21.0],
 'segmentation': [[190.0,
   492.5,
   179.0,
   492.5,
   172.5,
   488.0,
   170.5,
   480.0,
   175.0,
   473.5,
   190.0,
   471.5,
   196.5,
   476.0,
   198.5,
   484.0,
   190.0,
   492.5]],
 'width': 768,
 'height': 572}

## Creando JSON

# 1. Crear JSON y Array images

In [143]:
"""
 En el directorio "Con Mascara" y en particular "Castings" se recorrera cada carpeta y los ficheros .png
 seran añadidos al array de Imágenes, finalmente escrito en el fichero.
 Formato:
     height
     width
     id
     file_name 
"""
import json

# Pequeña funcion que guarda formateado al fichero el diccionario actual
def guardaJson(dic, fichero):
    with open(fichero, 'w') as fichero:
        json.dump(dic, fichero, indent = 4)
    fichero.close()

''' 
# PRUEBAS

fichero= '.'+os.sep+'IMG'+os.sep+'info.json'

datos = {}

datos['images'] = []
datos['images'].append({
    'height':5,
    'width': 1,
    'id': 'Dale canffdela'
})

datos['images'].append({
    'height':5,
    'width': 21,
    'id': 'Dafasfa'
})

guardaJson(datos,fichero)

''' 

" \n# PRUEBAS\n\nfichero= '.'+os.sep+'IMG'+os.sep+'info.json'\n\ndatos = {}\n\ndatos['images'] = []\ndatos['images'].append({\n    'height':5,\n    'width': 1,\n    'id': 'Dale canffdela'\n})\n\ndatos['images'].append({\n    'height':5,\n    'width': 21,\n    'id': 'Dafasfa'\n})\n\nguardaJson(datos,fichero)\n\n"

In [137]:
''' 
Funcion que recibe un directorio y un nombre para el fichero, escanea solo imagenes y no mascaras y
las registra en la primera seccion del JSON
'''

def registraImages(directorio, nombreJson):
    fichero = '.' + os.sep +'IMG'+ os.sep + nombreJson +'.json'
    datosJson = {}
    extensiones = [".png"]
    datosJson['images'] = []
    ID = 0
    for root, dirs, files in os.walk(directorio_imagenes):
        path = root.split(os.sep)
        if (os.path.basename(root) != 'masks'):
            for file in files:
                extension = os.path.splitext(file)[1]
                if extension in extensiones:
                    im = Image.open(root+os.sep+file)
                    height, width = im.size
                    datosJson['images'].append({
                        'height': height,
                        'width': width,
                        'id': ID,
                        'file_name': file
                    })
                    ID+=1
    return datosJson['images']

In [138]:
directorio_imagenes = '.'+os.sep+'IMG'
fichero = 'info'
registraImages(directorio_imagenes, fichero)

[{'height': 768, 'width': 572, 'id': 0, 'file_name': 'C0001_0001.png'},
 {'height': 768, 'width': 572, 'id': 1, 'file_name': 'C0001_0002.png'},
 {'height': 768, 'width': 572, 'id': 2, 'file_name': 'C0001_0003.png'},
 {'height': 768, 'width': 572, 'id': 3, 'file_name': 'C0001_0004.png'},
 {'height': 768, 'width': 572, 'id': 4, 'file_name': 'C0001_0005.png'},
 {'height': 768, 'width': 572, 'id': 5, 'file_name': 'C0001_0006.png'},
 {'height': 768, 'width': 572, 'id': 6, 'file_name': 'C0001_0007.png'},
 {'height': 768, 'width': 572, 'id': 7, 'file_name': 'C0001_0008.png'},
 {'height': 768, 'width': 572, 'id': 8, 'file_name': 'C0001_0009.png'},
 {'height': 768, 'width': 572, 'id': 9, 'file_name': 'C0001_0010.png'},
 {'height': 768, 'width': 572, 'id': 10, 'file_name': 'C0001_0011.png'},
 {'height': 768, 'width': 572, 'id': 11, 'file_name': 'C0001_0012.png'},
 {'height': 768, 'width': 572, 'id': 12, 'file_name': 'C0001_0013.png'},
 {'height': 768, 'width': 572, 'id': 13, 'file_name': 'C0001_

In [146]:
''' 
Funcion que recibe un directorio y un nombre para el fichero, segun las carpetas en IMG, 
genera una nueva categoria

'''

def registraCategories(directorio, nombreJson):
    fichero = '.' + os.sep +'IMG'+ os.sep + nombreJson +'.json'
    
    dir_list = next(os.walk('.' + os.sep +'IMG'))[1]
    
    datosJson = {}
    datosJson['categories'] = []
    ID = 0
    
    for d in dir_list:
        datosJson['categories'].append({
                            'supercategory': d,
                            'id': ID,
                            'name': d
                        })
        ID+=1
    return datosJson['categories']  
    

In [147]:
fichero = 'info'
registraCategories(directorio_imagenes, fichero)

[{'supercategory': 'Castings', 'id': 0, 'name': 'Castings'},
 {'supercategory': 'Welding', 'id': 1, 'name': 'Welding'},
 {'supercategory': 'Welds', 'id': 2, 'name': 'Welds'}]

In [148]:
''' 
Funcion que recibe un directorio y un nombre para el fichero, recorre imagenes y busca sus mascaras
genera la segmentacion y anotaciones y escribe en el JSON
'''

def registraAnnotations(directorio, nombreJson):
    datosJson = {}    
    fichero = '.' + os.sep +'IMG'+ os.sep + nombreJson +'.json'
    datosJson['images'] = registraImages(directorio_imagenes, fichero)
    datosJson['categories'] = registraCategories(directorio_imagenes, fichero)
    extensiones = [".png"]
    datosJson['annotations'] = []
    ID = 0
    IDImagen = 0
    for root, dirs, files in os.walk(directorio_imagenes):
        path = root.split(os.sep)
        if (os.path.basename(root) != 'masks'):
            for file in files:                
                extension = os.path.splitext(file)[1]
                if extension in extensiones:
                    directorio_mascaras = root + os.sep + 'masks'
                    for rootm, dirm, mascaras in os.walk(directorio_mascaras):
                        fileN = file.replace(extension,'')
                        for mascara in mascaras:                      
                            if fileN in mascara:
                                image = Image.open(directorio_mascaras+ os.sep+mascara)
                                data = asarray(image)
                                
                                annotation_id = ID
                                image_id = IDImagen
                                tolerance = 2
                                binary_mask = data
                                is_crowd = False
                                
                                if 'Castings' in path:
                                      category_info = {
                                            "id": 0,
                                            "is_crowd": False
                                        }
                                elif 'Welding' in path:
                                        category_info = {
                                            "id": 1,
                                            "is_crowd": False
                                        }
                                elif 'Welds' in path:
                                        category_info = {
                                            "id": 2,
                                            "is_crowd": False
                                        }
                                    
                                annotation = create_annotation_info(annotation_id, image_id, category_info, binary_mask, 
                           image_size=None, tolerance=2, bounding_box=None)
                                datosJson['annotations'].append(annotation)
                                ID+=1
                    IDImagen+=1
                
    guardaJson(datosJson,fichero)
                                


In [149]:
directorio_imagenes = '.'+os.sep+'IMG'
fichero = 'info'
registraAnnotations(directorio_imagenes, fichero)